### ISSUE TITLE
Lancement de tests échoue

### ISSUE THREAD

**Issue by mencattini** [cui-unige/petri-nets-mencattini#1]
Lors du lancement des tests (avec _busted_ **et** _wercker_), un test échoue de manière non prévisible et régulière.

Voici la capture d'écran :
![capture du 2016-10-13 11-24-01](https://cloud.githubusercontent.com/assets/16821049/19355331/46cba9ba-916a-11e6-9660-a810aaaf85a9.png)

Ici on voit que lors de deux lancés successifs, en moins d'une minute. Un échoue et l'autre réussi.
Ce qui est étonnant.

Voici un autre exemple (il s'agit toujours du même test qui échoue)
![capture du 2016-10-13 17-28-55](https://cloud.githubusercontent.com/assets/16821049/19355412/953b1cd4-916a-11e6-80d8-10c6e1c79acf.png)

Merci d'avance

**Comment by saucisson** [comment]
Le graphe de couverture a-t-il toujours la même taille, ou bien dépend-il de l'ordre dans lequel les états ont été parcourus ?

**Comment by mencattini** [comment]
J'utilise un itérateur ```Fun.each``` pour parcourir mes états dans la construction du graphe de couverture (_dans la fonction ```omegize(new_state,states)```_).

Pour ```Graph.__call```, j'ajoute les états dans l'ordre dans lequels ils sont rencontrés. Normalement
pour un type d'exploration (_largeur_ ou _profondeur_) *fixé* et pour un réseau de pétri *fixé*, on devrait toujours les parcourir dans le même ordre.

Dans les screenshots, que je mis ci-dessus, on a en altérnance la réussite et le succès. Mais en réalité, il se peut que cela réussisent deux fois de suite ou que cela échoue deux fois de suite. 
Voici un autre exemple
![capture du 2016-10-15 12-25-47](https://cloud.githubusercontent.com/assets/16821049/19409349/8454e724-92d2-11e6-857d-dd04094ec23a.png)

**Comment by saucisson** [comment]
Oui, mais cet ajout dépend de l'ordre dans lequel les transitions franchissables sont retournées par `state:enabled ()`. Cet ordre n'est pas garanti, car il repose sur une itération sur les transitions, qui ne sont pas ordonnées.
As-tu essayé d'afficher les états du graphe de couverture lorsque le test ne passe pas, et regardé si le résultat peut être correct ?

**Comment by mencattini** [comment]
Voici l'état du graphe de couverture quand le test passe:
```
p1=1,p2=0,p3=0,p4=0
p1=0,p2=0,p3=ω,p4=0
p1=1,p2=ω,p3=0,p4=0
p1=0,p2=ω,p3=ω,p4=0
p1=0,p2=ω,p3=ω,p4=ω
p1=ω,p2=ω,p3=ω,p4=ω
```

et voici le graphe lorsque le test ne passe pas:
```
p1=1,p2=0,p3=0,p4=0
p1=1,p2=ω,p3=0,p4=0
p1=0,p2=0,p3=1,p4=0
p1=0,p2=ω,p3=1,p4=0
p1=0,p2=ω,p3=1,p4=ω
p1=ω,p2=ω,p3=0,p4=ω
p1=ω,p2=ω,p3=ω,p4=ω
```
 ou bien celui là:
```
p1=1,p2=0,p3=0,p4=0
p1=0,p2=0,p3=1,p4=0
p1=1,p2=ω,p3=0,p4=0
p1=0,p2=ω,p3=1,p4=0
p1=0,p2=ω,p3=1,p4=ω
p1=ω,p2=ω,p3=0,p4=ω
p1=ω,p2=ω,p3=ω,p4=ω
```

Du coup, il y a effectivement un soucis lors de la création du graphe de couverture, pourtant j'itère sur tout les états pour trouver un qui est strictement plus petit que l'état courant. Puis j'ajoute les ```oméga```

**Comment by saucisson** [comment]
Le problème vient clairement de ta fonction `marking_lt`. Mais d'ailleurs, pourquoi l'as-tu réimplémentée, alors que  [le sujet](https://github.com/cui-unige/modeling-verification-1) t'indique que :

* Each state contains a `petrinet` field for its Petri net, a `marking` field for the marking of this state, and a `successors` field that maps transitions to the successor states.
* `m1 < m2` returns true if and only if (marking) `m1` is included in (marking) `m2`.

Ainsi avec la comparaison suivante, le résultat est toujours correct :
```lua
if state.marking <= new_state.marking then
  ...
```
Note que j'ai utilisé ici l'opérateur `<=` au lieu de `<` qui semble buggé. J'ai corrigé cet opérateur dans [le dépôt](https://github.com/cui-unige/modeling-verification-1).

L'implémentation correcte de cette fonction est donnée dans `marking/init.lua` par :
```lua
function Marking.__le (lhs, rhs)
  assert (getmetatable (lhs) == Marking)
  assert (getmetatable (rhs) == Marking)
  return Fun.all (function (place, valuation)
    local r = rhs [place]
    if not r then
      return false
    elseif r == Marking.omega   and valuation == Marking.omega   then
      return true
    elseif r == Marking.omega   and type (valuation) == "number" then
      return true
    elseif type (r) == "number" and type (valuation) == "number" then
      return valuation <= r
    elseif type (r) == "number" and valuation == Marking.omega   then
      return false
    end
  end, lhs)
end

function Marking.__lt (lhs, rhs)
  assert (getmetatable (lhs) == Marking)
  assert (getmetatable (rhs) == Marking)
  return lhs <= rhs
     and lhs ~= rhs
end
```

Quelle différence vois-tu avec ta propre version ?

**Comment by mencattini** [comment]
Effectivement en remplaçant,

```if state.marking < new_state.marking then```
par 
```if state.marking <= new_state.marking then```
Les tests passent toujours.

En fait j'ai réimplémenté la comparaison car l'opérateur ```<``` était beugé, et je me retrouvais dans une boucle infinie.

Merci de l'aide. Je clos l'issue.
